### ISSUE TITLE
Headless config not working

### ISSUE THREAD

**Issue by ghost** [stas2z/orangepi-build-cb1#2]
Wifi network configuration not working

Steps:

1. Flashed the image Bttcb1_3.0.6_debian_bookworm_minimal_linux5.16.17.img to SD card
2. mounted the SD card to linux 
3. copied the file /boot/armbian_first_run.txt.template to /boot/armbian_first_run.txt
4. Edited the wifi information and other options

**Comment by ghost** [comment]
FR_general_delete_this_file_after_completion=1
FR_net_change_defaults=1
FR_net_ethernet_enabled=0
FR_net_wifi_enabled=1
FR_net_wifi_ssid='my_2.4G_connection_id>'
FR_net_wifi_key='my_password'
FR_net_wifi_countrycode='GB'
FR_net_use_static=1
FR_net_static_ip='192.168.1.191'
FR_net_static_gateway='192.168.1.1'
FR_net_static_mask='255.255.255.0'
FR_net_static_dns='192.168.1.1 8.8.8.8'

**Comment by stas2z** [comment]
bookworm wifi is broken, it's not only cb1 issue, same for all orangepi images
use bullseye instead
