### ISSUE TITLE
Headless setup

### ISSUE THREAD

**Issue by ghost** [stas2z/orangepi-build-cb1#3]
Is it possible to do an headless setup like with BTT CB1 stock image?

**Comment by stas2z** [comment]
What does "headless" mean for you?

**Comment by ghost** [comment]
Setup without screen + keyboard.
For example on first poweron can show a temporary WIFI AP to connect to and configure WIFI, IP, Hostname or config file to be edited in /boot like BTT CB1 stock image.

**Comment by stas2z** [comment]
Ok, ic
it's just a modified orange pi builder to build cb1 image, everyone can do whatever they want with it)

but you can check my another repo with several orangepi images built with separate FAT16 /boot
https://github.com/stas2z/orange-pi-images/releases/tag/v0.1

**Comment by ghost** [comment]
I have tried with the image:
[Bttcb1_3.0.6_debian_bullseye_minimal_linux5.16.17.img.xz](https://github.com/stas2z/orange-pi-images/releases/download/v0.1/Bttcb1_3.0.6_debian_bullseye_minimal_linux5.16.17.img.xz)
But seems it is not booting or connecting properly. 
I tried static IP and DHCP but it is not reachable.
The led on CB1 stays on solid green.
I don't have a screen so i cannot debug it...

**Comment by stas2z** [comment]
ive checked mine cb1 with this image
image works flawlessly, it started up  and connected to wifi 
![Selection_1221](https://user-images.githubusercontent.com/5320135/231526675-8ee73516-c6d2-420d-9a97-645aa838dd95.jpg)

**Comment by stas2z** [comment]
Closed
